// src/components/common/IconMap.tsx
// Added 'bell' and 'refresh-cw' if they weren't explicitly present
import * as LucideIcons from "lucide-react";

export const iconMap = {
    'check-square': LucideIcons.CheckSquare,
    'calendar': LucideIcons.Calendar,
    'search': LucideIcons.Search,
    'user': LucideIcons.User,
    'settings': LucideIcons.Settings,
    'file-text': LucideIcons.FileText,
    'trash': LucideIcons.Trash2,
    'list': LucideIcons.List,
    'grid': LucideIcons.Grid,
    'clock': LucideIcons.Clock,
    'alert-circle': LucideIcons.AlertCircle,
    'plus': LucideIcons.Plus,
    'more-horizontal': LucideIcons.MoreHorizontal,
    'chevron-down': LucideIcons.ChevronDown,
    'chevron-up': LucideIcons.ChevronUp,
    'chevron-left': LucideIcons.ChevronLeft,
    'chevron-right': LucideIcons.ChevronRight,
    'sun': LucideIcons.Sun,
    'sunset': LucideIcons.Sunset,
    'moon': LucideIcons.Moon,
    'calendar-plus': LucideIcons.CalendarPlus,
    'edit': LucideIcons.Edit3,
    'check': LucideIcons.Check,
    'x': LucideIcons.X,
    'arrow-left': LucideIcons.ArrowLeft,
    'arrow-right': LucideIcons.ArrowRight,
    'star': LucideIcons.Star,
    'flag': LucideIcons.Flag,
    'tag': LucideIcons.Tag,
    'bell': LucideIcons.Bell, // Added for date picker
    'share': LucideIcons.Share2,
    'upload': LucideIcons.UploadCloud,
    'download': LucideIcons.Download,
    'logout': LucideIcons.LogOut,
    'lock': LucideIcons.Lock,
    'tool': LucideIcons.Wrench,
    'layers': LucideIcons.Layers,
    'package': LucideIcons.Package,
    'sliders': LucideIcons.SlidersHorizontal,
    'info': LucideIcons.Info,
    'help': LucideIcons.HelpCircle,
    'phone': LucideIcons.Phone,
    'mail': LucideIcons.Mail,
    'external-link': LucideIcons.ExternalLink,
    'crown': LucideIcons.Crown,
    'terminal': LucideIcons.Terminal,
    'grip-vertical': LucideIcons.GripVertical,
    'copy': LucideIcons.Copy,
    'archive': LucideIcons.Archive,
    'arrow-up-down': LucideIcons.ArrowUpDown,
    'calendar-days': LucideIcons.CalendarDays,
    'loader': LucideIcons.Loader2,
    'users': LucideIcons.Users,
    'sparkles': LucideIcons.Sparkles,
    'folder-plus': LucideIcons.FolderPlus,
    'folder': LucideIcons.Folder,
    'minus': LucideIcons.Minus,
    'inbox': LucideIcons.Inbox,
    'x-circle': LucideIcons.XCircle,
    'calendar-check': LucideIcons.CalendarCheck,
    'refresh-cw': LucideIcons.RefreshCw, // Added for date picker
};

export type IconName = keyof typeof iconMap;